// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9s1jcAapZgbtrjR68hmj6BQmAy3xDCfU',
    appId: '1:1077690826514:web:1abeca16bc8409fdbafdcb',
    messagingSenderId: '1077690826514',
    projectId: 'athlo-63ed2',
    authDomain: 'athlo-63ed2.firebaseapp.com',
    storageBucket: 'athlo-63ed2.firebasestorage.app',
    measurementId: 'G-KZHLDQN5H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6rvbRkX9FYJlZB-xZ8CgwlmnB5WDkkdo',
    appId: '1:1077690826514:android:8f5805469b83ee1cbafdcb',
    messagingSenderId: '1077690826514',
    projectId: 'athlo-63ed2',
    storageBucket: 'athlo-63ed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9prku4bkVgwnQ68RrVHmi2JrmK8lazag',
    appId: '1:1077690826514:ios:367b61e2135402ebbafdcb',
    messagingSenderId: '1077690826514',
    projectId: 'athlo-63ed2',
    storageBucket: 'athlo-63ed2.firebasestorage.app',
    iosBundleId: 'com.example.athlo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9prku4bkVgwnQ68RrVHmi2JrmK8lazag',
    appId: '1:1077690826514:ios:367b61e2135402ebbafdcb',
    messagingSenderId: '1077690826514',
    projectId: 'athlo-63ed2',
    storageBucket: 'athlo-63ed2.firebasestorage.app',
    iosBundleId: 'com.example.athlo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9s1jcAapZgbtrjR68hmj6BQmAy3xDCfU',
    appId: '1:1077690826514:web:72c834c3d018ba97bafdcb',
    messagingSenderId: '1077690826514',
    projectId: 'athlo-63ed2',
    authDomain: 'athlo-63ed2.firebaseapp.com',
    storageBucket: 'athlo-63ed2.firebasestorage.app',
    measurementId: 'G-M0F1QTHTKE',
  );
}
